### ISSUE TITLE
[self setEditing:false animated:true];调用无效

### ISSUE THREAD

**Issue by jacpy** [JazysYu/JZTableViewRowAction#7]
如果当前包含UITableView的ViewController不是继承UITableViewController，而是继承UIViewController,然后自己添加UITableView，那么[self setEditing:false animated:true];不起作用；如果是继承自UITableViewController则不会有问题。
是什么梗？求解！

**Comment by JazysYu** [comment]
[self.tableView setEditing:false animated:true]

**Comment by jacpy** [comment]
已解决，谢谢！
